backend:
  name: git-gateway
  branch: Article # 您的 Git 分支名稱

media_folder: "public/img" # 媒體檔案儲存位置
public_folder: "/img" # 媒體檔案的公開路徑

collections:
  - name: "articles" # 集合名稱
    label: "文章" # 集合標籤
    folder: "content/articles" # 文章檔案儲存位置
    create: true # 允許建立新文章
    slug: "{{slug}}" # 文章 slug 的格式
    fields: # 文章欄位
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime" }
      - { label: "內容", name: "body", widget: "markdown" }
      - { label: "作者", name: "author", widget: "string" }
      - { label: "標籤", name: "tags", widget: "list" }
      - { label: "特色圖片", name: "image", widget: "image" }
      - { label: "摘要", name: "excerpt", widget: "text" }
      - { label: "狀態", name: "status", widget: "select", options: ["草稿", "已發佈"] }
      - { label: "精選", name: "featured", widget: "boolean" }
      - { label: "SEO 標題", name: "seo_title", widget: "string" }
      - { label: "SEO 描述", name: "seo_description", widget: "text" }
      - { label: "版面配置", name: "layout", widget: "select", options: ["default", "blog", "article"] }
